### ISSUE TITLE
The Haiku style for BreakConstructorInitializers doesn't work if constructor is declared inline

### ISSUE THREAD

**Issue by pulkomandy** [owenca/haiku-format#15]
```
struct BView::LayoutData {
	LayoutData()
		:
		fMinSize(),
		fMaxSize(),
		fPreferredSize(),
		fAlignment(),
		fLayoutInvalidationDisabled(0),
		fLayout(NULL),
		fLayoutContext(NULL),
		fLayoutItems(5, false),
		fLayoutValid(true),		// TODO: Rethink these initial values!
		fMinMaxValid(true),		//
		fLayoutInProgress(false),
		fNeedsRelayout(true)
	{
	}
```

Gets reformatted to:

```
struct BView::LayoutData
{
	LayoutData()
		: fMinSize(),
		fMaxSize(),
		fPreferredSize(),
		fAlignment(),
		fLayoutInvalidationDisabled(0),
		fLayout(NULL),
		fLayoutContext(NULL),
		fLayoutItems(5, false),
		fLayoutValid(true), // TODO: Rethink these initial values!
		fMinMaxValid(true), //
		fLayoutInProgress(false),
		fNeedsRelayout(true)
	{
	}
```

There should be a newline after the :

**Comment by owenca** [comment]
```
struct X {
	f() : a() {}
}
```
Should the above be formatted as below??
```
struct {
	f()
		:
		a()
	{
	}
}
```

**Comment by pulkomandy** [comment]
In this special case (with a single thing in the initializer list and nothing inside the braces), maybe it would be better to keep it on one line. But I'd say that's not too important, is that case happening often in Haiku?

**Comment by owenca** [comment]
Not sure how common it occurs in Haiku. If the constructor is declared outside of `struct X`, should the colon be on its own line like the following?
```
X::X()
	:
	a()
{
}
```

**Comment by pulkomandy** [comment]
Yes, that's how it's done in https://www.haiku-os.org/development/coding-guidelines/

> // The ':' always comes on its own line, initializers following

**Comment by owenca** [comment]
I know in general the colon should be on its own line but wanted to rule out the special case when there is only one item in the list. :)

**Comment by pulkomandy** [comment]
The comment clearly says "always" so there doesn't seem to be any exception :)
