### ISSUE TITLE
std::nothrow gets extra spacing

### ISSUE THREAD

**Issue by pulkomandy** [owenca/haiku-format#17]
Output of haiku-format:

```
return new (std::nothrow) BView(data);
```

There shouldn't be a space between new and (std::nothrow)

**Comment by owenca** [comment]
This is the behavior of clang-format because `new` is an operator like `switch`. Will see if it can be overridden.

**Comment by saloniig** [comment]
Hello,
The problem was SpaceBeforeParens contain new keyword as the control statement. 
I have created a Pull Request here : https://github.com/viveris/llvm-project/pull/1
Please review.
Thanks

**Comment by owenca** [comment]
Done in 88f7234.
