### ISSUE TITLE
' : ' should come on its own line and initializers in following lines

### ISSUE THREAD

**Issue by saloniig** [owenca/haiku-format#18]
Output of haiku-format :

`	Renderer() : fTitle(NULL), fPrimaryIcon(NULL), fSelected(false) {}
`

The colon ' :  ' should come in its own line and rest initializers should come in following line according to haiku guidelines as shown below : 

```
Renderer()
	:
	fTitle(NULL),
	fPrimaryIcon(NULL),
	fSelected(false)
```

**Comment by saloniig** [comment]
Hello,
I have created a pull request for this [here](https://github.com/viveris/llvm-project/pull/2).
Please review.
Thanks

**Comment by owenca** [comment]
This was already fixed in the very first version of haiku-format 223b308 2+ years ago. It still works with the current version:
```
~/haiku-format> haiku-format -version
haiku-format version 10.0.1 (https://github.com/owenca/haiku-format.git c1fcbd5407f081ccfa472ce94a73014e6da368c3)
~/haiku-format> haiku-format
Renderer() : fTitle(NULL), fPrimaryIcon(NULL), fSelected(false) {}
Renderer()
        :
        fTitle(NULL),
        fPrimaryIcon(NULL),
        fSelected(false)
{
}
~/haiku-format> 
```
