### ISSUE TITLE
Wrongly added spaces in long nested conditions

### ISSUE THREAD

**Issue by humdingerb** [owenca/haiku-format#2]
You have a very long nested condition that'll get broken up:
```
bool
App::QuitRequested()
{
	if (someVeryVeryLongConditionThatBarelyFitsOnALine && (someOtherLongishCondition || someOtherEvenLongerNestedConditionPart2)) {
		return false;
	} else
		return true;
}
```

It does mostly the right thing, but three spaces are put in front of the last term ```   || someOtherEvenLongerNestedConditionPart2)) {```

**Comment by owenca** [comment]
Just verified that it's a bug in clang-format. Will try to fix it.

**Comment by owenca** [comment]
Fixed.
