### ISSUE TITLE
Braces removed in else statement having more than one statement

### ISSUE THREAD

**Issue by saloniig** [owenca/haiku-format#21]
According to haiku-format there should be braces in else condition which contain more than one statement as shown below:
```
else {
	for (int i = 0; i < fDeviceListView->CountItems(); i++) {
		DeviceListItemView* item =
			dynamic_cast<DeviceListItemView*>(
				fDeviceListView->ItemAt(i));
		if (item != NULL && item->Label() == name) {
			fDeviceListView->RemoveItem(i);
			BView* settings = fCardView->ChildAt(i);
			fCardView->RemoveChild(settings);
			delete settings;
			break;
		}
	}
}
```

but the clang-format gives output as:

```
else 
	for (int i = 0; i < fDeviceListView->CountItems(); i++) {
		DeviceListItemView* item =
			dynamic_cast<DeviceListItemView*>(
				fDeviceListView->ItemAt(i));
		if (item != NULL && item->Label() == name) {
			fDeviceListView->RemoveItem(i);
			BView* settings = fCardView->ChildAt(i);
			fCardView->RemoveChild(settings);
			delete settings;
			break;
		}
	}
```
which is not according to haiku gudelines and need to be correct.

**Comment by pulkomandy** [comment]
Fixed with https://github.com/viveris/llvm-project/commit/ca492a8015c091fccb4fd1cc6f910f2f1a48a99b, https://github.com/viveris/llvm-project/commit/d69e542e38fb23c834cd96feac961498ff2c1cf4, and https://github.com/viveris/llvm-project/commit/c5377b0c71dab755a2dc121f9e14b015d4a4d122

**Comment by owenca** [comment]
This had already been taken care of in 680f261.
