### ISSUE TITLE
Extra space before ++ operator in for loop

### ISSUE THREAD

**Issue by saloniig** [owenca/haiku-format#22]
The output of clang format results in extra space before ++ operator in for loop which needs to be correct as it doesn't follow haiku guidelines [(example)](https://review.haiku-os.org/c/haiku/+/3826/1/src/preferences/input/MouseSettings.cpp#386)

**Comment by owenca** [comment]
This is a duplicate of #16 and was already taken care of in 3387c83 6+ months ago.
