### ISSUE TITLE
Empty functions to inline

### ISSUE THREAD

**Issue by saloniig** [owenca/haiku-format#23]
Empty functions should be converted to inline like :

`Foo::~Foo() {}`

**Comment by saloniig** [comment]
Hello,
I have created a pull request for this [here](https://github.com/viveris/llvm-project/pull/2).
Please review.
Thanks

**Comment by owenca** [comment]
Haiku Coding Guidelines only gives an example of an empty-body function inside a class declaration. When such functions are defined outside of class declarations, the braces are not wrapped:
```
~/haiku-format> cat Foo.cpp
class Foo
{
        Foo()
        {
        }

        ~Foo();   
};

Foo::~Foo() {}
~/haiku-format> haiku-format Foo.cpp
class Foo
{
        Foo() {}

        ~Foo();
};


Foo::~Foo()
{
}
~/haiku-format> 
```
