### ISSUE TITLE
Structure initializers should be written with one field per line

### ISSUE THREAD

**Issue by saloniig** [owenca/haiku-format#24]
Output of haiku-format converts [703](https://git.haiku-os.org/haiku/tree/src/add-ons/kernel/file_systems/xfs/kernel_interface.cpp#n703) and [704](https://git.haiku-os.org/haiku/tree/src/add-ons/kernel/file_systems/xfs/kernel_interface.cpp#n704) line number into one line which is against haiku guidelines.

**Comment by owenca** [comment]
The line links above are bad. Can you attach the test case here?

**Comment by saloniig** [comment]
I have updated the links now. Here is the link of output : [output](https://editor.mergely.com/fL9EhMvz/)

**Comment by owenca** [comment]
Thanks for updating the links. Have you tested it against clang-format 10.0.1 or 12.0.0?

**Comment by saloniig** [comment]
This issue has been solved.
https://github.com/viveris/llvm-project/commit/df2208a9e66f87a1bd6f0bd68ed973ace901427b
It can be closed now.

Thanks
