### ISSUE TITLE
Add a ReadMe.md with usage

### ISSUE THREAD

**Issue by humdingerb** [owenca/haiku-format#25]
A ReadMe could clarify if I use haiku-format correctly. :)
Am I correct, that I have to get the "_haiku-format" file from this repo, rename it to ".haiku-format" and place it in the folder _above_ the source file I want to format?

As an asided, how can we include a ".haiku-format" file in the HPKG? Just put it in /system/data/haiku-format/ and point to it in the --help text?

**Comment by owenca** [comment]
> A ReadMe could clarify if I use haiku-format correctly. :)

Added README.md in 8941428.

> Am I correct, that I have to get the "_haiku-format" file from this repo, rename it to ".haiku-format" and place it in the folder _above_ the source file I want to format?

You can just run install.sh which copies _haiku-format to your home directory and renames it to .haiku-format.

> As an asided, how can we include a ".haiku-format" file in the HPKG? Just put it in /system/data/haiku-format/ and point to it in the --help text?

Perhaps do something in the recipe similar to what install.sh does?

**Comment by humdingerb** [comment]
OK, I'll update the recipe accordingly.

Is what I wrote correct, if you want to override ` /boot/home/.haiku-format`:
> place [".haiku-format"] in the folder above the source file I want to format?

**Comment by owenca** [comment]
@humdingerb Yep! For example, when formatting the files in `/boot/home/Filer/sources`, haiku-format will look for the config file starting at the `sources` subdirectory and moving up along the directory tree until a `.haiku-format` file is found. I will add a link to the clang-format [documentation](https://releases.llvm.org/10.0.0/tools/clang/docs/ClangFormat.html) in `README.md`.

**Comment by owenca** [comment]
> OK, so it doesn't default to the one in the Home folder in the end, e.g. when my project is on another partition?

Correct.

> We just put the .haiku-format file into Home, becaue it's convenient to move elsewhere from there. Rigth?

I thought putting `.haiku-format` in `/boot/home` would be most convenient for the user as it would cover all source directories under the home directory.

**Comment by humdingerb** [comment]
Alright. For now the HPKG will have the .haiku-format file in $dataDir/haiku-format and will execute a post-install script to copy it to /boot/home/.
I guess it would be nicer if haiku-format would look into ~/config/settings/ if it doesn't find a .haiku-format file in the project hierarchy.

**Comment by owenca** [comment]
@humdingerb Can you wait for a few days? I will add the feature so that you can place the config file directly into `~/config/settings`.

**Comment by humdingerb** [comment]
That'd be brilliant!
