### ISSUE TITLE
Update _haiku-format (cast & char limit)

### ISSUE THREAD

**Issue by humdingerb** [owenca/haiku-format#26]
I think most of the Haiku code doesn't insert a space after a cast, e.g.:

`BIconUtils::GetVectorIcon((const uint8*)data, size, icon) == B_OK)`
not
`BIconUtils::GetVectorIcon((const uint8*) data, size, icon) == B_OK)`

Then it should be `SpaceAfterCStyleCast: false`

And since we upped the char limit, it'd be `ColumnLimit: 100`

**Comment by owenca** [comment]
> I think most of the Haiku code doesn't insert a space after a cast, e.g.:

IIRC the Haiku style required the space, and I fixed so many of them whenever they were in my path. :) Do you mind confirming it with other devs and maybe add an example in the style guide? I will update the option value if needed.

> And since we upped the char limit, it'd be `ColumnLimit: 100`

Done in 00fa71b.

**Comment by humdingerb** [comment]
After I have completed drafting a mail to the haiku-dev ML, I found that casts _are_ operators - as you can see, I'm a "self-taught" amateur coding dabbler :) - and therefore fall into what's already in the style guide:
> Always separate operators with a space on both sides, and use a space after comma.

So you were right all along... :)

**Comment by owenca** [comment]
> and therefore fall into what's already in the style guide:
>
> > Always separate operators with a space on both sides, and use a space after comma.

That's correct for most binary operators (when the operator and its operands are on the same line), but there are some exceptions: e.g. `.` and `->`. For unary operators, usually there is no space between the operator and its operand: e.g. `-a`, `b++`, `*c`, `&d`, etc.

Also, what about `new` followed by `(` as in #17?
