### ISSUE TITLE
Enhancement: do not wrap braces before a catch block

### ISSUE THREAD

**Issue by nielx** [owenca/haiku-format#28]
I am aware that this is not the place to discuss Haiku's coding style, but I would like to capture that I will make the proposal to do not wrap braces before `catch` blocks. 

Currently, the formatting is set to `BraceWrapping` with `BeforeCatch: true`. This leads to the following formatting:

```
	try {
		status.code = std::stol(statusCodeString);
	}
	catch (...) {
		throw BNetworkRequestError(__PRETTY_FUNCTION__, BNetworkRequestError::ProtocolError);
	}
```

Instead, I prefer:

```
	try {
		status.code = std::stol(statusCodeString);
	} catch (...) {
		throw BNetworkRequestError(__PRETTY_FUNCTION__, BNetworkRequestError::ProtocolError);
	}
```

Much like `if else`, there is a relationship between the blocks that IMO is better expressed by having the closing of the try or previous catch block align directly with the opening of the next.

**Comment by owenca** [comment]
Done in 88f7234.
