### ISSUE TITLE
Enhancement: default SpaceBeforeRangeBasedForLoopColon to false

### ISSUE THREAD

**Issue by nielx** [owenca/haiku-format#29]
I am aware that this is not the place to discuss Haiku's coding style, but I would like to capture that I will make the proposal to require that there is no space before the colon in range-based for loops. This means setting `SpaceBeforeRangeBasedForLoopColon` to `false`. 

Example:
```
    for(auto v: values) {
```

**Comment by owenca** [comment]
See https://discuss.haiku-os.org/t/haiku-coding-guidelines-and-haiku-format/14047.
