### ISSUE TITLE
Messing up indention of .h files

### ISSUE THREAD

**Issue by humdingerb** [owenca/haiku-format#30]
Currently, haiku-format removes the special indention of header files. I attach an example:

original: 
[DataSource.h.txt](https://github.com/owenca/haiku-format/files/12908931/DataSource.h.txt)

snippet:

```
class MemoryDataSource : public DataSource {
public:
						MemoryDataSource();
	virtual				~MemoryDataSource();

	virtual void		Print(BString& text, int64 value) const;
	virtual const char*	Unit() const;
};
```

-----

haiku-formatted: 
[DataSource_formatted.h.txt](https://github.com/owenca/haiku-format/files/12908932/DataSource_formatted.h.txt)

snippet:

```
class MemoryDataSource : public DataSource
{
public:
	MemoryDataSource();
	virtual ~MemoryDataSource();

	virtual void Print(BString& text, int64 value) const;
	virtual const char* Unit() const;
};
```

**Comment by owenca** [comment]
Duplicate of #19.

**Comment by humdingerb** [comment]
Sorry, don't know how I missed that...
