### ISSUE TITLE
Set SpaceAfterCStyleCast to 'false'

### ISSUE THREAD

**Issue by nielx** [owenca/haiku-format#32]
Currently `haiku-format` seems to be configured to add spaces after C-style casts, see [this example](https://review.haiku-os.org/c/haiku/+/7302/comment/6c5d749c_a1e4cef8/). While not documented explicitly, in my thinking it is more common to not have spaces after a cast.

The [SpaceAfterCStyleCast](https://clang.llvm.org/docs/ClangFormatStyleOptions.html#spaceaftercstylecast) is set to `true` in the current (17.0.6) configuration. It should likely be set to false.

Will do a quick community survey to validate.

**Comment by owenca** [comment]
See https://github.com/owenca/haiku-format/issues/26#issuecomment-1272616809, though it would be a simple change if the [Haiku style](https://www.haiku-os.org/development/coding-guidelines/) is updated to say the contrary.

**Comment by nielx** [comment]
https://discuss.haiku-os.org/t/haiku-style-format-rfc-c-style-casts-and-spaces/14557

**Comment by nielx** [comment]
Looks like a [consensus was reached](https://discuss.haiku-os.org/t/haiku-style-format-rfc-c-style-casts-and-spaces/14557/8?u=nielx), can the style be updated for the next release?

**Comment by owenca** [comment]
Yep.
