### ISSUE TITLE
Incorrect configuration for BraceWrapping: Afterclass

### ISSUE THREAD

**Issue by nielx** [owenca/haiku-format#33]
Tested with `haiku-format` 17.0.6 and noticed in [Change 7720](https://review.haiku-os.org/c/haiku/+/7720). The expectation is that the brace is at the same line as the class declaration. It seems like the BraceWrapping, AfterClass should be set to false. See [the documentation](https://clang.llvm.org/docs/ClangFormatStyleOptions.html#bracewrapping) and the [Coding Guidelines](https://www.haiku-os.org/development/coding-guidelines).

**Comment by owenca** [comment]
There are examples of both in the coding guidelines and the codebase.

**Comment by nielx** [comment]
I see the discrepancies now, not great. However, I do not think there is any need for discussion/polling, from my (subjective) pov most of our code is using the proposed style. I will correct the coding guidelines, and if there is no push back, I think we have our answer.
