### ISSUE TITLE
Add curlies around multi-line statements

### ISSUE THREAD

**Issue by humdingerb** [owenca/haiku-format#7]
Add curly brackets around multi-line statements (even if it's only a 
single statement that needs more than one line).
E.g.:

```
if (clear)
	memset((void*) frameBuffer, 0,
		gKernelArgs.frame_buffer.physical_buffer.size);
```
should be:
```
if (clear) {
	memset((void*) frameBuffer, 0,
		gKernelArgs.frame_buffer.physical_buffer.size);
}
```

**Comment by pulkomandy** [comment]
Also take into account the case where there are comments. For example:

```
	} else {
		// no clipping region
		link.Attach<int32>(-1);
	}
```

incorrectly is reformatted to:

```
	} else // no clipping region
		link.Attach<int32>(-1);
```

**Comment by owenca** [comment]
See https://github.com/owenca/haiku-format/issues/5#issuecomment-741035179.

**Comment by owenca** [comment]
Done in 88f7234.
