### ISSUE TITLE
Use boolean conditions, instead of pointer/integer logic

### ISSUE THREAD

**Issue by humdingerb** [owenca/haiku-format#9]
Not sure, if it's possible...

Instead of:
```
if (pointer)
...
if (!pointer)
```
use:
```
if (pointer != NULL)
...
if (pointer == NULL)
```

**Comment by owenca** [comment]
I'm almost certain that this rule cannot be handled by a code formatter, which must know the data type of the variable. On the other hand, it can be easily handled by the compiler. Keep it open for now...

**Comment by owenca** [comment]
It doesn't look like something suitable for haiku-format to handle.
